services:

    _defaults:
        autowire: true
        autoconfigure: true
        public: true
        
    Application\Controller\:
        resource: '../../../src/Application/Controller/*'
        
    controller.landing:
        alias: 'Application\Controller\Landing'
        
    controller.packages:
        alias: 'Application\Controller\PackagesController'